# Top comment from Ron
jobs:
  - job:
    name: Go 1.1
    image: go1.1
    build:
      - ls -la
      - sleep 5
  - job:
    name: Go 1.2
    image: go1.1
    build:
      - ls -la
      - sleep 5
notifications:
  email:
    enabled: true
    recipients:
      - cavepig@drone.io
    on_success: true
    on_failure: true
  http:
    enabled: true
    urls:
      - http://example.com/drone_endpoint
  hipchat:
    enabled: false
    room: Testjob Build Notifications


